name: Flutter CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
#      - name: Analyze code
#        run: flutter analyze || true

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk